# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================


### server properties

server:
  servlet:
    context-path: /async-demo
  
### application properties

spring:
  application:
    name: async-demo
      
### logging properties

logging:
  level:
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %blue(%thread) | %5p | %logger | %m%n"
